### ISSUE TITLE
Error with phpstan 0.11 and phpstan-prophecy 0.5.0

### ISSUE THREAD

**Issue by temp** [Jan0707/phpstan-prophecy#84]
When install phpstan-prophecy 0.5.0 with phpstan 0.11 I get this error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method PHPStan\Type\Generic\TemplateTypeMap::createEmpty() in /phpstan/vendor/jangregor/phpstan-prophecy/src/Reflection/ObjectProphecyMethodReflection.php:62
Stack trace:
#0 /phpstan/vendor/phpstan/phpstan/src/Analyser/Scope.php(1443): JanGregor\Prophecy\Reflection\ObjectProphecyMethodReflection->getVariants()
#1 /phpstan/vendor/phpstan/phpstan/src/Analyser/Scope.php(372): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#2 /phpstan/vendor/phpstan/phpstan/src/Rules/RuleLevelHelper.php(160): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\MethodCall))
#3 /phpstan/vendor/phpstan/phpstan/src/Rules/Methods/CallMethodsRule.php(72): PHPStan\Rules\RuleLevelHelper->findTypeToCheck(Object(PHPStan\Analyser\Scope), Object(PhpParser\Node\Expr\MethodCall), 'Call to method ...', Object(Closure))
#4 /phpstan/vendor/phpstan/phpstan/src/Analyser/Analyser.php(155): PHPStan\Rules\Methods\CallMethodsRule->processNode(Object(PhpParser\Node\Expr\MethodCall), O in /phpstan/vendor/jangregor/phpstan-prophecy/src/Reflection/ObjectProphecyMethodReflection.php on line 62
```
No error with 0.4.2, so I guess users that are stuck with phpstan 0.11 should pin phpstan-prophecy to ~0.4.0, since 0.5.1 is already 0.12 only...

**Comment by localheinz** [comment]
Alternatively, update `phpstan/phpstan`. 

Sorry for the troubles.
